// SPDX-License-Identifier: MIT OR Apache-2.0

//! 2026-09-29: The Markdown rendering of a [`VennReport`]: the report the `new-model` method
//! checks in as `kernels/circuits/venn/<target>-vs-<arch>.md`.
//!
//! Owner: metrale-circuit (venn).
//! Invariants: the text is a pure function of the report; numbers print at fixed precision, so
//! a regenerated report is byte-identical and `--check` can compare it.

use std::fmt::Write as _;

use super::families::{EvidenceSource, ParamKind};
use super::report::{Row, VennReport};
use super::{Class, Compared, Finding};
use crate::ir::LayerKind;

fn short(recipe: &str) -> &str {
    recipe.rsplit('/').next().unwrap_or(recipe)
}

fn base(path: &str) -> &str {
    path.rsplit('/').next().unwrap_or(path)
}

fn compared(f: &Finding) -> String {
    match &f.compared {
        Compared::Model {
            recipe,
            node,
            kernels,
        } => format!("{}: `{kernels}` ({} `{node}`)", f.family, short(recipe)),
        Compared::Point { how, files } => {
            let more = if files.len() > 1 {
                format!(" +{}", files.len() - 1)
            } else {
                String::new()
            };
            format!(
                "{}: {} in `{}`{more}; no compared model runs this op on it here",
                f.family,
                how.name(),
                base(&files[0])
            )
        }
    }
}

fn diffs(f: &Finding) -> (String, String) {
    if f.diffs.is_empty() {
        return ("none".into(), "-".into());
    }
    let what: Vec<String> = f
        .diffs
        .iter()
        .map(|d| format!("{} {} vs {}", d.param, d.target, d.other))
        .collect();
    let kinds: Vec<&str> = f.diffs.iter().map(|d| d.kind.name()).collect();
    (what.join("; "), kinds.join("; "))
}

fn evidence(f: &Finding, r: &VennReport) -> String {
    if f.evidence.is_empty() {
        return "none".into();
    }
    f.evidence
        .iter()
        .map(|e| match e {
            EvidenceSource::Measurement(k) => match r.cited.get(k) {
                Some(p) => format!("`{k}` ({p:.1}% of floor)"),
                None => format!("`{k}`"),
            },
            EvidenceSource::Microbench(m) => format!("microbench: {m}"),
        })
        .collect::<Vec<_>>()
        .join("; ")
}

fn pointed(f: &Finding, kind: ParamKind) -> Vec<&str> {
    f.diffs
        .iter()
        .filter(|d| d.kind == kind)
        .map(|d| d.param.as_str())
        .collect()
}

fn decision(row: &Row) -> String {
    let Some(f) = &row.primary else {
        return "build: reference kernel, logits parity, then microbench against its roofline"
            .into();
    };
    let mut out = match f.class {
        Class::Shared => "reuse (optimized at this point)".to_string(),
        Class::SharedUnmeasured => "reuse, then microbench at this point".to_string(),
        Class::PolicyVariant => format!(
            "policy template on {} (or split + bit_identical fusion rule)",
            pointed(f, ParamKind::Policy).join(", ")
        ),
        Class::ParameterizationOpportunity => {
            let mut s = format!("template on {}", pointed(f, ParamKind::Compile).join(", "));
            let pol = pointed(f, ParamKind::Policy);
            if !pol.is_empty() {
                let _ = write!(s, " + policy {}", pol.join(", "));
            }
            s.push_str("; stability gate at existing points");
            s
        }
        Class::Novel => String::new(),
    };
    if f.instantiated == Some(super::families::How::Copy) {
        out.push_str("; the target point exists only as a file copy");
    }
    for a in &row.also {
        let params: Vec<&str> = a
            .diffs
            .iter()
            .filter(|d| d.kind != ParamKind::Runtime)
            .map(|d| d.param.as_str())
            .collect();
        let _ = write!(
            out,
            "; also {}: {} ({})",
            a.family,
            a.class.name(),
            params.join(", ")
        );
    }
    out
}

fn kind_name(k: Option<LayerKind>) -> &'static str {
    k.map_or("head / draft", LayerKind::name)
}

/// 2026-09-29: Render `r` as Markdown.
pub fn render(r: &VennReport) -> String {
    let mut s = String::new();
    let t = &r.target;
    let against: Vec<&str> = r.against.iter().map(|a| a.checkpoint.as_str()).collect();
    let _ = writeln!(
        s,
        "# Kernel Venn: {} vs {}\n",
        t.checkpoint,
        against.join(", ")
    );
    let _ = writeln!(
        s,
        "Generated by `{}`. Do not edit: regenerate with that command, and `--check` verifies it is current.\n",
        r.command
    );
    s.push_str("## Target\n\n| | |\n|---|---|\n");
    let _ = writeln!(s, "| Recipe | `{}` |", t.recipe);
    let _ = writeln!(s, "| Checkpoint | `{}` |", t.checkpoint);
    let _ = writeln!(s, "| Circuit | `kernels/circuits/{}.toml` |", r.arch);
    let _ = writeln!(s, "| Kernel target | `{}` |", t.target);
    let mut kinds: Vec<(LayerKind, usize)> = Vec::new();
    for k in &r.layer_kinds {
        match kinds.iter_mut().find(|(x, _)| x == k) {
            Some((_, n)) => *n += 1,
            None => kinds.push((*k, 1)),
        }
    }
    let kinds: Vec<String> = kinds
        .iter()
        .map(|(k, n)| format!("{n} {}", k.name()))
        .collect();
    let _ = writeln!(
        s,
        "| Layers | {}: {} |",
        r.layer_kinds.len(),
        kinds.join(", ")
    );
    let dims: Vec<String> = t
        .shape
        .dims
        .iter()
        .map(|(k, v)| format!("{k} {v}"))
        .collect();
    let _ = writeln!(s, "| Dims | {} |", dims.join(", "));
    let set: Vec<String> = t
        .policy
        .settings
        .iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect();
    let _ = writeln!(s, "| Settings | {} |\n", set.join(" "));
    s.push_str("### Declared precision (weight / input activation per site)\n\n| Site | Weight | Activation |\n|---|---|---|\n");
    for (site, (w, a)) in &r.precision {
        let _ = writeln!(s, "| `{site}` | {w} | {a} |");
    }
    s.push_str(
        "\n## Compared with\n\n| Recipe | Checkpoint | Circuit | Settings |\n|---|---|---|---|\n",
    );
    for a in &r.against {
        let set: Vec<String> = a
            .policy
            .settings
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect();
        let _ = writeln!(
            s,
            "| `{}` | `{}` | `{}` | {} |",
            a.recipe,
            a.checkpoint,
            a.arch,
            set.join(" ")
        );
    }
    if !r.uncovered.is_empty() {
        s.push_str(
            "\n## Compared models without full rules\n\nThese compared models are not golden: no \
             FUSIONS.toml rule covers the sites below, so they are planned by placeholders and run \
             no family here (a target op they share is not reported as theirs).\n\n| Recipe | Mode | \
             Rows | Sites |\n|---|---|---|---|\n",
        );
        for u in &r.uncovered {
            let sites: Vec<String> = u.sites.iter().map(|x| format!("`{x}`")).collect();
            let _ = writeln!(
                s,
                "| `{}` | {} | {} | {} |",
                u.recipe,
                u.run.mode.name(),
                u.run.rows,
                sites.join(", ")
            );
        }
    }
    let rf = &r.roofline;
    let _ = writeln!(
        s,
        "\n## Estimate\n\nStep share is a roofline estimate from edge shapes and formats, per node: \
         max(bytes / {:.1} GB/s, FLOPs / peak), with peaks BF16 {:.1}, FP8 {:.1} and NVFP4 {:.1} TFLOPS \
         (the MMA class of the node's input activation). State traffic: the paged KV cache over {} \
         tokens per sequence, and FP32 recurrent states read and written once per sequence. Routed \
         experts read E(1 - (1 - k/E)^T) distinct experts for T tokens. Launch overhead and conv \
         windows are not counted. Replace with measured profiles once a serve runs.\n",
        rf.dram_gbps, rf.bf16_tflops, rf.fp8_tflops, rf.nvfp4_tflops, rf.context_tokens
    );
    s.push_str("## Flags: layers that cannot batch rows\n\n");
    if r.flags.is_empty() {
        s.push_str("None.\n");
    } else {
        s.push_str("| # | Layer kind | Mode | Rows | Est. added time | vs. multi-row step | Source | Note |\n|---|---|---|---|---|---|---|---|\n");
        for (i, f) in r.flags.iter().enumerate() {
            let _ = writeln!(
                s,
                "| {} | {} | {} | {} | {:.1} µs | +{:.1}% | {} | {} |",
                i + 1,
                kind_name(f.layer_kind),
                f.run.mode.name(),
                f.run.rows,
                f.added_us,
                100.0 * f.share,
                f.source,
                f.note
            );
        }
    }
    for tb in &r.tables {
        let _ = writeln!(
            s,
            "\n## {}, {} row{} (estimated step {:.1} µs)\n",
            tb.run.mode.name(),
            tb.run.rows,
            if tb.run.rows == 1 { "" } else { "s" },
            tb.total_us
        );
        s.push_str("| # | Phase | Target op | Comparison kernel | Class | Parameter(s) differing | Runtime / compile-time / policy | Est. step share | Evidence at target point | Decision |\n|---|---|---|---|---|---|---|---|---|---|\n");
        for (i, row) in tb.rows.iter().enumerate() {
            let fmt = match (&row.weight, &row.activation) {
                (Some(w), Some(a)) => format!(", W {w}, A {a}"),
                (None, Some(a)) => format!(", in {a}"),
                _ => String::new(),
            };
            let (cmp, class, (what, kinds), ev) = match &row.primary {
                Some(f) => (compared(f), f.class.name(), diffs(f), evidence(f, r)),
                None => (
                    "no family implements it".to_string(),
                    Class::Novel.name(),
                    ("-".to_string(), "-".to_string()),
                    "none".to_string(),
                ),
            };
            let _ = writeln!(
                s,
                "| {} | {} | `{}` ×{} (`{}`{fmt}) | {cmp} | {class} | {what} | {kinds} | {:.1}% ({:.1} µs) | {ev} | {} |",
                i + 1,
                tb.run.mode.name(),
                row.site,
                row.count,
                row.op,
                100.0 * row.share,
                row.time_us,
                decision(row)
            );
        }
    }
    super::render_summary::summary(r, &mut s);
    s
}
