// SPDX-License-Identifier: MIT OR Apache-2.0

//! 2026-10-10: The Markdown rendering of a [`UnionReport`] (`kernels/circuits/venn/UNION.md`).
//!
//! Owner: metrale-circuit (venn).
//! Invariants: the text is a pure function of the report; numbers print at fixed precision and
//! every table is ordered deterministically, so a regenerated report is byte-identical.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use super::union::{Envelope, SiteUse, UnionReport};
use super::{Class, Run};
use crate::rules::Mode;

/// 2026-10-10: The two runs every per-model share is quoted at: C1 and C16.
pub(super) fn key_runs(r: &UnionReport) -> Vec<Run> {
    r.runs
        .iter()
        .copied()
        .filter(|x| {
            (x.mode == Mode::Decode && x.rows == 1) || (x.mode == Mode::MultiSeq && x.rows == 16)
        })
        .collect()
}

pub(super) fn run_name(r: Run) -> String {
    match r.mode {
        Mode::Decode => format!("C{}", r.rows),
        _ => format!("{} C{}", r.mode.name(), r.rows),
    }
}

pub(super) fn pct(x: f64) -> String {
    format!("{:.1}%", 100.0 * x)
}

pub(super) fn letter(u: &SiteUse) -> &'static str {
    match (u.class, u.envelope) {
        (_, Envelope::Shape) => "E",
        (_, Envelope::Point) => "M",
        (Class::Shared | Class::SharedUnmeasured, _) => "U",
        (Class::PolicyVariant, _) => "V",
        (Class::ParameterizationOpportunity, _) => "O",
        (Class::Novel, _) => "N",
    }
}

fn rank(l: &str) -> u8 {
    match l {
        "E" => 0,
        "M" => 1,
        "U" => 2,
        "O" => 3,
        "V" => 4,
        _ => 5,
    }
}

/// 2026-10-10: The family a use counts under: its primary family, or `novel:<op>`.
pub(super) fn family_of(u: &SiteUse) -> String {
    match (&u.family, u.class) {
        (Some(f), c) if c != Class::Novel => f.clone(),
        _ => format!("novel:{}", u.op),
    }
}

pub(super) fn point_text(u: &SiteUse) -> String {
    if u.point.is_empty() {
        return "-".into();
    }
    u.point
        .iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect::<Vec<_>>()
        .join(" ")
}

/// 2026-10-10: Render the union.
pub fn render_union(r: &UnionReport, command: &str) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "# Union kernel Venn: every circuit instance\n\nGenerated by `{command}`. Do not edit: \
         regenerate with that command; the test fails on a stale copy.\n\nEach model is the \
         target of a Venn report (`met circuit venn`) against the golden instances ({}), at {}. \
         Classes and step shares are those reports' (roofline estimates, not profiles). A site is \
         **in envelope** (E) when it is Shared and a measurement covers its shape (the record \
         names its N and K, or was taken on the model's own kernel target); **M** is Shared at \
         the family point and row count but measured at other shapes only; **U** shared \
         unmeasured; **V** policy variant; **O** parameterization opportunity; **N** novel. \
         Shares summed over models are in model-steps (each model's step is 100%).\n",
        r.against
            .iter()
            .map(|a| format!("`{a}`"))
            .collect::<Vec<_>>()
            .join(", "),
        r.runs
            .iter()
            .map(|x| run_name(*x))
            .collect::<Vec<_>>()
            .join(", ")
    );
    models(&mut s, r);
    envelope(&mut s, r);
    matrix(&mut s, r);
    vocabulary(&mut s, r);
    saturation(&mut s, r);
    super::union_tables::shapes(&mut s, r);
    super::union_tables::plan(&mut s, r);
    super::union_tables::novel(&mut s, r);
    s
}

fn models(s: &mut String, r: &UnionReport) {
    s.push_str("## Models\n\n| # | Recipe | Checkpoint | Circuit | Golden | Layers |");
    for x in &r.runs {
        let _ = write!(s, " Est. step {} (ms) |", run_name(*x));
    }
    s.push_str("\n|---|---|---|---|---|---|");
    s.push_str(&"---|".repeat(r.runs.len()));
    s.push('\n');
    for (i, m) in r.models.iter().enumerate() {
        let layers: Vec<String> = m.layers.iter().map(|(k, n)| format!("{n} {k}")).collect();
        let _ = write!(
            s,
            "| M{} | `{}` | `{}` | `{}` | {} | {} |",
            i + 1,
            m.recipe,
            m.checkpoint,
            m.arch,
            if m.golden { "yes" } else { "no" },
            layers.join(", ")
        );
        for x in &r.runs {
            let _ = write!(
                s,
                " {:.2} |",
                m.step_us.get(x).copied().unwrap_or(0.0) / 1000.0
            );
        }
        s.push('\n');
    }
}

fn envelope(s: &mut String, r: &UnionReport) {
    s.push_str(
        "\n## In-envelope step share per model\n\nShare of each model's estimated step by \
         envelope status.\n\n| Model | Run | E (in envelope) | M (point only) | U | O | V | N |\n\
         |---|---|---:|---:|---:|---:|---:|---:|\n",
    );
    for (i, m) in r.models.iter().enumerate() {
        for x in key_runs(r) {
            let mut by: BTreeMap<&str, f64> = BTreeMap::new();
            for u in r.uses.iter().filter(|u| u.model == i && u.run == x) {
                *by.entry(letter(u)).or_insert(0.0) += u.share;
            }
            let g = |l: &str| pct(by.get(l).copied().unwrap_or(0.0));
            let _ = writeln!(
                s,
                "| M{} `{}` | {} | {} | {} | {} | {} | {} | {} |",
                i + 1,
                short(&m.recipe),
                run_name(x),
                g("E"),
                g("M"),
                g("U"),
                g("O"),
                g("V"),
                g("N")
            );
        }
    }
}

pub(super) fn short(recipe: &str) -> &str {
    recipe.rsplit('/').next().unwrap_or(recipe)
}

fn matrix(s: &mut String, r: &UnionReport) {
    let mut cells: BTreeMap<String, BTreeMap<usize, &'static str>> = BTreeMap::new();
    for u in &r.uses {
        let e = cells
            .entry(family_of(u))
            .or_default()
            .entry(u.model)
            .or_insert("N");
        if rank(letter(u)) < rank(e) {
            *e = letter(u);
        }
    }
    let mut rows: Vec<(&String, &BTreeMap<usize, &str>)> = cells.iter().collect();
    rows.sort_by(|a, b| b.1.len().cmp(&a.1.len()).then_with(|| a.0.cmp(b.0)));
    s.push_str(
        "\n## Family x model matrix\n\nBest status of any site of the model on the family over \
         every run (E/M/U shared, O parameterization opportunity, V policy variant, N novel); \
         `novel:<op>` rows are ops no family implements.\n\n| Family | Models |",
    );
    for i in 0..r.models.len() {
        let _ = write!(s, " M{} |", i + 1);
    }
    s.push_str("\n|---|---:|");
    s.push_str(&"---|".repeat(r.models.len()));
    s.push('\n');
    for (fam, by) in rows {
        let _ = write!(s, "| `{fam}` | {} |", by.len());
        for i in 0..r.models.len() {
            let _ = write!(s, " {} |", by.get(&i).copied().unwrap_or(""));
        }
        s.push('\n');
    }
}

fn vocabulary(s: &mut String, r: &UnionReport) {
    let mut by: BTreeMap<&str, BTreeSet<usize>> = BTreeMap::new();
    for u in &r.uses {
        by.entry(u.op.as_str()).or_default().insert(u.model);
    }
    let one: Vec<String> = by
        .iter()
        .filter(|(_, m)| m.len() == 1)
        .map(|(op, m)| format!("`{op}` (M{})", m.iter().next().map_or(0, |x| x + 1)))
        .collect();
    let _ = writeln!(
        s,
        "\n## Op vocabulary\n\n{} distinct ops (a linear projection counts per role, an \
         activation quantizer per format); {} recur in two or more models, {} appear in one.\n\n\
         | Op | Models | Which |\n|---|---:|---|",
        by.len(),
        by.values().filter(|m| m.len() > 1).count(),
        one.len()
    );
    let mut rows: Vec<_> = by.iter().collect();
    rows.sort_by(|a, b| b.1.len().cmp(&a.1.len()).then_with(|| a.0.cmp(b.0)));
    for (op, m) in rows {
        let which: Vec<String> = m.iter().map(|x| format!("M{}", x + 1)).collect();
        let _ = writeln!(s, "| `{op}` | {} | {} |", m.len(), which.join(" "));
    }
    let _ = writeln!(s, "\nOps in one model only: {}.", one.join(", "));
}

fn saturation(s: &mut String, r: &UnionReport) {
    s.push_str(
        "\n## Saturation curve\n\nIn order of addition (INSTANCES.toml order): what each model \
         brings that no earlier model needed. Families are primary families; points are \
         (family, compile-time and policy point); novel ops are ops no family implements.\n\n\
         | Model | Ops | New ops | Families | New families | New family points | New novel ops | \
         Cum. ops | Cum. families | Cum. family points |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n",
    );
    let (mut ops, mut fams, mut points, mut novel) = (
        BTreeSet::new(),
        BTreeSet::new(),
        BTreeSet::new(),
        BTreeSet::new(),
    );
    for (i, m) in r.models.iter().enumerate() {
        let mine: Vec<&SiteUse> = r.uses.iter().filter(|u| u.model == i).collect();
        let my_ops: BTreeSet<&str> = mine.iter().map(|u| u.op.as_str()).collect();
        let my_fams: BTreeSet<String> = mine
            .iter()
            .filter(|u| u.class != Class::Novel)
            .filter_map(|u| u.family.clone())
            .collect();
        let my_points: BTreeSet<(String, String)> = mine
            .iter()
            .filter(|u| u.class != Class::Novel)
            .filter_map(|u| u.family.clone().map(|f| (f, point_text(u))))
            .collect();
        let my_novel: BTreeSet<&str> = mine
            .iter()
            .filter(|u| u.class == Class::Novel)
            .map(|u| u.op.as_str())
            .collect();
        let new_ops = my_ops.iter().filter(|o| !ops.contains(**o)).count();
        let new_fams = my_fams.iter().filter(|f| !fams.contains(*f)).count();
        let new_points = my_points.iter().filter(|p| !points.contains(*p)).count();
        let new_novel = my_novel.iter().filter(|o| !novel.contains(**o)).count();
        ops.extend(my_ops.iter().map(|o| o.to_string()));
        fams.extend(my_fams.iter().cloned());
        points.extend(my_points.iter().cloned());
        novel.extend(my_novel.iter().map(|o| o.to_string()));
        let _ = writeln!(
            s,
            "| M{} `{}` | {} | {new_ops} | {} | {new_fams} | {new_points} | {new_novel} | {} | {} | {} |",
            i + 1,
            short(&m.recipe),
            my_ops.len(),
            my_fams.len(),
            ops.len(),
            fams.len(),
            points.len()
        );
    }
}
